# Configuration file for SpawnEggDrops plugin
# You can set your own drop percentages and drop amounts here
# If you set a number that's more/less than the set maximum/minimum, plugin will automatically use the default value

# SPAWN EGG DROP PERCENTAGE
# This will apply to all drops
# (Default = 10; Min = 1; Max = 100)
spawn_egg_drop_percentage: 10

# SPAWN EGG DROP AMOUNT
# This will apply to all drops
# (Default = 1; Min = 1; Max = 10)
spawn_egg_drop_amount: 1

# DROPS FROM MOBS SPAWNED FROM SPAWNERS
# This will apply to all drops for mobs from spawners
# (Default = true; Options = true / false)
drops_from_spawners: true

# Version 1.2.1 works for MC versions 1.21 - 1.21.10
# End of config file